In [1]:
'''
Estimateur steps :
    read in data (normalize if necessary)
    Train/Test split the data 
    Create Estimateur Feature Columns 
    Create input Estimateur Function 
    Train Estimateur model
    Predict with new Test input function 
    
'''

'\nEstimateur steps :\n    read in data (normalize if necessary)\n    Train/Test split the data \n    Create Estimateur Feature Columns \n    Create input Estimateur Function \n    Train Estimateur model\n    Predict with new Test input function \n    \n'

In [2]:
import pandas as pd 

In [3]:
df = pd.read_csv("iris.csv")

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [6]:
 '''
  in order to use tensorFlow object there some few thing to respect 
  one thing the actual columns names must mot have any special char
  the target must be an integer
 '''
    #renames the columns 
df.columns = ["sepal_length","sepal_width","petal_length","petal_width","target"]
df.head()

sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2     0.0
1           4.9          3.0           1.4          0.2     0.0
2           4.7          3.2           1.3          0.2     0.0
3           4.6          3.1           1.5          0.2     0.0
4           5.0          3.6           1.4          0.2     0.0

In [7]:
df["target"] = df["target"].apply(int)

In [8]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [9]:
y = df["target"]

In [11]:
x = df.drop("target",axis=1)

In [12]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [13]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [14]:
 from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [19]:
import tensorflow as tf 

In [22]:
#create features columns 

In [24]:
x.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [25]:
featcols =[]
for cols in x.columns:
    featcols.append(tf.feature_column.numeric_column(cols))
featcols

[NumericColumn(key='sepal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='sepal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='petal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='petal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [26]:
# create input function or two one for training other for evaluation


In [27]:
input_func = tf.estimator.inputs.pandas_input_fn(x=x_train,y=y_train,batch_size=10,num_epochs=5,shuffle=True)

In [30]:
#create an estimateur 

In [48]:
classifier = tf.estimator.DNNClassifier(hidden_units = [10,30,20,1020,10],n_classes=3,feature_columns=featcols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpfnbcfg7q', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f4511c45050>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [49]:
# training part 

In [50]:
classifier.train(input_fn= input_func,steps=50)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpfnbcfg7q/model.ckpt.
INFO:tensorflow:loss = 10.924178, step = 1
INFO:tensorflow:Saving checkpoints for 50 into /tmp/tmpfnbcfg7q/model.ckpt.
INFO:tensorflow:Loss for final step: 4.7497582.


In [51]:
#evaluate the model 


In [52]:
#create prediction function 

In [53]:
pred_functi = tf.estimator.inputs.pandas_input_fn(x = x_test,batch_size=len(x_test),shuffle=False)

In [54]:
predictions =list( classifier.predict(input_fn=pred_functi))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpfnbcfg7q/model.ckpt-50
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [55]:
predictions

[{'logits': array([-1.5878639,  1.4007545,  1.2267025], dtype=float32),
  'probabilities': array([0.0266353 , 0.52892977, 0.44443494], dtype=float32),
  'class_ids': array([1]),
  'classes': array([b'1'], dtype=object),
  'all_class_ids': array([0, 1, 2], dtype=int32),
  'all_classes': array([b'0', b'1', b'2'], dtype=object)},
 {'logits': array([ 4.6354876, -7.480859 , -8.996219 ], dtype=float32),
  'probabilities': array([9.9999332e-01, 5.4693378e-06, 1.2017725e-06], dtype=float32),
  'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'all_class_ids': array([0, 1, 2], dtype=int32),
  'all_classes': array([b'0', b'1', b'2'], dtype=object)},
 {'logits': array([-4.549236 ,  3.2930598,  4.061719 ], dtype=float32),
  'probabilities': array([1.2440087e-04, 3.1672984e-01, 6.8314576e-01], dtype=float32),
  'class_ids': array([2]),
  'classes': array([b'2'], dtype=object),
  'all_class_ids': array([0, 1, 2], dtype=int32),
  'all_classes': array([b'0', b'1', b'2'], dtype=objec

In [56]:
final_pred = []

for pred in predictions:
    final_pred.append(pred["class_ids"][0])
final_pred

[1,
 0,
 2,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 1,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 2,
 1,
 1,
 0,
 0,
 1,
 2,
 2,
 1,
 2]

In [57]:
#final predds

In [58]:
from sklearn.metrics import classification_report,confusion_matrix

In [59]:
print(confusion_matrix(y_test,final_pred))

[[19  0  0]
 [ 0 14  1]
 [ 0  2 14]]


In [60]:
print(classification_report(y_test,final_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.88      0.93      0.90        15
           2       0.93      0.88      0.90        16

    accuracy                           0.94        50
   macro avg       0.94      0.94      0.94        50
weighted avg       0.94      0.94      0.94        50

